FROM ubuntu:22.04

RUN apt update && apt install -y python3 python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY main.py .
COPY requirements.txt .

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0" ]
