FROM ubuntu:24

RUN apt update && apt install -y python3 python3-pip python3.12-venv && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv .venv && source .venv/bin/activate

WORKDIR /app
COPY main.py .
COPY requirements.txt .

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0" ]
