FROM python:3.12-alpine

RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

RUN adduser --disabled-password --gecos "" --home "/nonexistent" --shell "/sbin/nologin" --no-create-home "app"

WORKDIR /app
COPY . .

RUN pip3 install -r requirements.txt

USER app:app

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0" ]
